Sorin foca
SkillBrain-com/RisingStars-QAC-G1-15-09-22 pull request #8
Opened 2022-11-22 19:12 UTC by sorinfoca

2022-11-22 19:26 UTC, anabmaria commented
need to add reviewers

2022-11-24 15:34 UTC, pmadalina88 approved these changes

2022-11-24 15:47 UTC, sorinfoca commented
> need to add reviewers

how?

2022-11-24 16:18 UTC, anabmaria requested changes
need to add homework in a folder with your name

2022-11-24 18:11 UTC, closed without merging